Implemented code for splitpane menu (#1wut88u)
hotwax/fulfillment pull request #24
Opened 2021-12-17 13:03 UTC by azkyakhan

![Splitpane](https://user-images.githubusercontent.com/82817616/146548631-25bcb414-aa18-4a7e-839f-d4553c77d08d.png)

2021-12-17 13:45 UTC, dt2patel approved these changes
looks good to me

2021-12-20 07:08 UTC, azkyakhan commented
![picklist-size-menu-desktop](https://user-images.githubusercontent.com/82817616/146726277-c9f6afc4-f969-4ef7-9ac1-c302f0ccee1f.png)
![menu](https://user-images.githubusercontent.com/82817616/146726291-5db3c762-60a1-4b54-9c23-7b7132ce0f9d.png)

![picklist-size-menu-mobile](https://user-images.githubusercontent.com/82817616/146726307-517d45b8-8469-4ef9-abc1-c6554ddabb78.png)

![spiltpane-menu](https://user-images.githubusercontent.com/82817616/146726312-76421420-a14d-4d66-9f8e-f5084951dc84.png)

2021-12-20 13:15 UTC, adityasharma7 requested changes

2021-12-20 13:15 UTC, adityasharma7 commented on src/App.vue
> +    <PicklistMenu content-id="main-content" />
I think we could move it to open orders

2021-12-20 13:15 UTC, adityasharma7 commented on src/components/PicklistMenu.vue
> +<template>
Improve component name

2021-12-20 13:15 UTC, adityasharma7 commented on src/components/PicklistMenu.vue
> +            <ion-label>10 orders</ion-label>
Add internationalisation

2021-12-23 05:50 UTC, adityasharma7 requested changes

2021-12-23 07:36 UTC, azkyakhan commented on src/App.vue
> +    <PicklistMenu content-id="main-content" />
Done

2021-12-23 07:36 UTC, azkyakhan commented on src/components/PicklistMenu.vue
> +<template>
Done

2021-12-23 07:36 UTC, azkyakhan commented on src/components/PicklistMenu.vue
> +            <ion-label>10 orders</ion-label>
DOne

2021-12-23 07:36 UTC, azkyakhan commented on src/components/Menu.vue
> +        <ion-menu-toggle auto-hide="false" v-for="(p, i) in appPages" :key="i">
Done

2021-12-23 07:37 UTC, azkyakhan commented on src/components/Menu.vue
> +            <ion-label>{{ p.title }}</ion-label>
Done

2021-12-23 09:20 UTC, azkyakhan commented on src/components/Menu.vue
> +        <ion-title>Broadway {{ $t("Store") }}</ion-title>
Done

2022-01-10 10:10 UTC, adityasharma7 approved these changes

2022-01-10 10:10 UTC, merged