Implemented: added the functionality to the popover buttons in the mobile view of completed orders page (#244)
hotwax/fulfillment pull request #256
Opened 2023-08-25 07:13 UTC by amansinghbais

### Related Issues
Related Issue: #244

### Short Description and Why It's Useful
- Added the functionality to the popover buttons in the mobile view of the completed orders page in fulfillment app.
- Added a new button for "Shipping label error" and added functionality to it in the popover present in mobile view of completed orders page.
- Added a new disabled button for the shipped item in mobile view.

### Screenshots of Visual Changes before/after (If There Are Any)
Before

![Screenshot from 2023-08-25 12-39-02](https://github.com/hotwax/fulfillment-pwa/assets/69574321/8631e82a-04cb-4bcd-9f52-997bded884ec)

After
![Screenshot from 2023-08-25 12-40-09](https://github.com/hotwax/fulfillment-pwa/assets/69574321/0b5387cf-ee42-4983-a8ba-9075b1b0cda1)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-08-29 11:22 UTC, ymaheshwari1 requested changes

2023-08-29 11:22 UTC, ymaheshwari1 commented on src/views/ShippingPopover.vue
>          {{ $t("Shipping label") }}
Update the labels to match them with desktop view

2023-09-22 05:05 UTC, k2maan requested changes

2023-09-22 05:05 UTC, k2maan commented on src/views/Completed.vue
> +          (this as any)[selectedMethod](order);
Functions can be async also.

2024-07-17 09:24 UTC, ymaheshwari1 commented
Closing as the UI of the app is getting changed and there is no immediate requirement for mobile view support.

2024-07-17 09:24 UTC, closed without merging