Implemented: mobile view support for the inprogress page of fulfillment app (#244)
hotwax/fulfillment pull request #258
Opened 2023-08-31 13:06 UTC by amansinghbais

### Related Issues

Closes #244

### Short Description and Why It's Useful

Implemented the mobile view for the inprogress page in the fulfillment app.
- Implemented the EditPackagingModal and ReportIssueModal so as to display order details and items in the modal.
- Added the functionality to the modal's popovers and buttons.

### Screenshots of Visual Changes before/after (If There Are Any)

Before
![Screenshot from 2023-08-31 18-19-58](https://github.com/hotwax/fulfillment-pwa/assets/69574321/b0dde20d-eea3-40d3-8d9e-4e9ac67468ce)
![Screenshot from 2023-08-31 18-26-35](https://github.com/hotwax/fulfillment-pwa/assets/69574321/69f5e7b3-4a2a-4c79-b371-2743f8aab125)
![Screenshot from 2023-08-31 18-30-51](https://github.com/hotwax/fulfillment-pwa/assets/69574321/2e73d619-1d7e-43f0-847e-33ae05013c72)

After
![Screenshot from 2023-08-31 18-23-38](https://github.com/hotwax/fulfillment-pwa/assets/69574321/5891782a-5df2-40e4-81c9-bb1153842ac3)
![Screenshot from 2023-08-31 18-26-20](https://github.com/hotwax/fulfillment-pwa/assets/69574321/b0bf9b58-83ef-4b71-809e-6094f0087df2)
![Screenshot from 2023-08-31 18-26-04](https://github.com/hotwax/fulfillment-pwa/assets/69574321/f5e7d08d-9a18-41b6-84c7-6e33585d0ea1)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-08-31 13:34 UTC, k2maan requested changes

2023-08-31 13:34 UTC, k2maan commented on src/views/EditPackagingModal.vue
> +      getFeature
Follow alphabetical order for exports

2023-08-31 13:34 UTC, k2maan commented on src/views/ReportIssueModal.vue
> +    <ion-card>
Fix indentation

2023-08-31 13:34 UTC, k2maan commented on src/views/EditPackagingModal.vue
> +              <Image :src="getProduct(item.productId).mainImageUrl" />
We should use the ShopifyImage component with the image size as small.

2023-08-31 13:34 UTC, k2maan commented on src/views/PackagingPopover.vue
> +        refresh
Fix indentation and follow alphabetical sorting

2023-08-31 13:34 UTC, k2maan commented on src/views/ReportIssueModal.vue
> +          <ion-select-option v-for="reason in rejectReasons" :key="reason.enumId" :value="reason.enumId">{{ reason.description ? $t(reason.description) : reason.enumId }}</ion-select-option>
Translate` reason.description `only if all description entries are added in the label json files.

2023-08-31 13:34 UTC, k2maan commented on src/views/ReportIssueModal.vue
> +      getFeature
Follow alphabetical sorting

2023-09-18 05:56 UTC, k2maan approved these changes

2024-07-17 09:25 UTC, ymaheshwari1 commented
Closing as the apps UI is getting changed and there is no immediate requirement of mobile support.

2024-07-17 09:25 UTC, closed without merging