Implemented Option to View Full-Size Image On Click (#283)
hotwax/fulfillment pull request #365
Opened 2023-12-05 09:36 UTC by shanmukhdutt

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

2023-12-12 09:37 UTC, k2maan requested changes

2023-12-12 09:37 UTC, k2maan commented on src/components/ImageModal.vue
> +	<ion-page>
Fix indentation throughout

2023-12-12 09:37 UTC, k2maan commented on src/views/Completed.vue
> +    async openImgModal(item: any){
```suggestion
    async openImageModal(item: any){
```

2023-12-12 09:37 UTC, k2maan commented on src/views/Completed.vue
> +      const imgModal = await modalController.create({
```suggestion
      const imageModal = await modalController.create({
```

2023-12-12 09:37 UTC, k2maan commented on src/views/Completed.vue
> +    async openImgModal(item: any){
Fix in other files as well.

2023-12-13 10:36 UTC, ymaheshwari1 reviewed
Update the PR with main branch and add the full size image support for kit products as well on all the pages

2023-12-13 10:36 UTC, ymaheshwari1 commented on src/components/ImageModal.vue
> +  name: 'DisplayImg',
```suggestion
  name: 'ImageModal',
```

2024-09-17 13:22 UTC, closed without merging