Added OMS information on settings page(#1y2ract)
hotwax/fulfillment pull request #42
Opened 2022-01-28 07:26 UTC by disha1202

2022-01-31 09:47 UTC, ymaheshwari1 requested changes
Add changelog entry file

2022-01-31 09:55 UTC, disha1202 commented
> Add changelog entry file

Added changelog entry

2022-01-31 10:07 UTC, ymaheshwari1 approved these changes

2022-02-04 10:10 UTC, adityasharma7 approved these changes

2022-02-04 10:10 UTC, merged