Implemented: facility dropdown is optional & select the current logged in facility (#585)
hotwax/fulfillment pull request #590
Opened 2024-06-20 04:32 UTC by R-Sourabh

### Related Issues

#585 

### Short Description and Why It's Useful
- Made the facility mapping optional.
- If user does not select/ map the facility the , payload will contain the selected current facility of the application.

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/fulfillment#contribution-guideline)

2024-06-20 10:44 UTC, ymaheshwari1 requested changes

2024-06-20 10:44 UTC, ymaheshwari1 commented on src/views/UploadImportOrders.vue
> +        'externalFacilityId': order[this.fieldMapping['facilityId'].value] ? order[this.fieldMapping['facilityId'].value] : this.currentFacility?.facilityId,
We can't pass facilityId here as the column is used to map using externalFacilityId

2024-06-20 12:47 UTC, ymaheshwari1 requested changes

2024-06-20 12:47 UTC, ymaheshwari1 commented on src/views/UploadImportOrders.vue
> +        'externalFacilityId': order[this.fieldMapping['facilityId'].value] ? order[this.fieldMapping['facilityId'].value] : this.currentFacility?.facilityId,
We need to pass facilityId as a separate key, if mapping is not available.

2024-06-24 06:04 UTC, dt2patel commented
Need to map order id to order id, not order id value

2024-06-24 13:11 UTC, ymaheshwari1 approved these changes

2024-06-24 13:19 UTC, merged