Implemented: barcode identifier selector and scanning based on selected identifier (#845)
hotwax/fulfillment pull request #846
Opened 2024-11-06 06:52 UTC by amansinghbais

### Related Issues

#845

### Short Description and Why It's Useful

Added support for the barcode identification scanning.

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/fulfillment#contribution-guideline)

2024-11-07 10:27 UTC, ravilodhi commented on src/views/Settings.vue
> +      barcodeContentMessage: translate("Only allow received quantity to be incremented by scanning the barcode of products. If the identifier is not found, the scan will default to using the internal
"Only allow received quantity......"  should be changed to "Only allow shipped quantity"

2024-11-07 10:31 UTC, ravilodhi commented on src/store/modules/util/actions.ts
> +  async cretaBarcodeIdentificationPref({ commit }) {
Correct typo.

2024-11-07 13:25 UTC, ymaheshwari1 requested changes

2024-11-07 13:25 UTC, ymaheshwari1 commented on src/store/modules/util/UtilState.ts
> +  barcodeIdentificationPref: any;
```suggestion
  barcodeIdentificationPref: string;
```

2024-11-07 13:25 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +    // default value when creating a scan setting
```suggestion
    // default value when creating a store setting
```

2024-11-07 13:25 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +  async updateBarcodeIdentificationPref({ commit }, payload) {
This action is not used anywhere, we should use this method wherever we are updating the state for barcode identifier, also we need to clear the barcode identifier value of logout.

2024-11-07 13:25 UTC, ymaheshwari1 commented on src/store/modules/util/index.ts
> +    barcodeIdentificationPref: ""
As we have defined `internalName` as default value for barcodeIdentifier we can have the same value here in state as its default declaration

2024-11-12 06:56 UTC, closed without merging

2024-11-12 06:56 UTC, amansinghbais commented
Closing this PR since latest commit got stuck in github glitch, Processing updates